import { EvaluationMethod } from '../types/evaluation';

export const EVALUATION_METHODS: EvaluationMethod[] = [
  {
    id: 'rubrica',
    atomicNumber: 1,
    symbol: 'Rb',
    name: 'Rúbrica',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Avanzado',
    formativeAction: 'Evaluar',
    modality: 'Práctica',
    icon: 'Table',
    description: 'Matriz de valoración que establece criterios y niveles de calidad para evaluar el desempeño de los estudiantes de forma transparente.',
    gridX: 1,
    gridY: 1,
  },
  {
    id: 'prueba-escrita',
    atomicNumber: 14,
    symbol: 'Pe',
    name: 'Prueba Escrita',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Intermedio',
    formativeAction: 'Conocer',
    modality: 'Escritura',
    icon: 'FileText',
    description: 'Instrumento tradicional para medir conocimientos adquiridos al final de un ciclo o unidad de aprendizaje.',
    gridX: 14,
    gridY: 1,
  },
  {
    id: 'portafolio',
    atomicNumber: 15,
    symbol: 'Pt',
    name: 'Portafolio',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Avanzado',
    formativeAction: 'Sintetizar',
    modality: 'Escritura',
    icon: 'FolderOpen',
    description: 'Colección sistemática de trabajos del estudiante que demuestra su esfuerzo, progreso y logros a lo largo del tiempo.',
    gridX: 1,
    gridY: 2,
  },
  {
    id: 'lista-cotejo',
    atomicNumber: 16,
    symbol: 'Lc',
    name: 'Lista de Cotejo',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Básico',
    formativeAction: 'Evaluar',
    modality: 'Práctica',
    icon: 'ListChecks',
    description: 'Instrumento estructurado que registra la presencia o ausencia de determinados rasgos, conductas o aprendizajes.',
    gridX: 2,
    gridY: 2,
  },
  {
    id: 'ensayo',
    atomicNumber: 27,
    symbol: 'Es',
    name: 'Ensayo',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Avanzado',
    formativeAction: 'Analizar',
    modality: 'Escritura',
    icon: 'PenTool',
    description: 'Texto escrito donde el estudiante analiza, interpreta o evalúa un tema, demostrando su capacidad de argumentación y síntesis.',
    gridX: 13,
    gridY: 2,
  },
  {
    id: 'mapa-conceptual',
    atomicNumber: 29,
    symbol: 'Mc',
    name: 'Mapa Conceptual',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Intermedio',
    formativeAction: 'Sintetizar',
    modality: 'Escritura',
    icon: 'Network',
    description: 'Representación gráfica que permite evaluar la comprensión de conceptos y las relaciones jerárquicas entre ellos.',
    gridX: 1,
    gridY: 3,
  },
  {
    id: 'debate',
    atomicNumber: 30,
    symbol: 'Db',
    name: 'Debate',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Avanzado',
    formativeAction: 'Dialogar',
    modality: 'Oralidad',
    icon: 'MessagesSquare',
    description: 'Discusión estructurada que evalúa la capacidad de argumentación, escucha activa y pensamiento crítico frente a un tema.',
    gridX: 2,
    gridY: 3,
  },
  {
    id: 'autoevaluacion',
    atomicNumber: 31,
    symbol: 'Au',
    name: 'Autoevaluación',
    evaluationType: 'Autoevaluación',
    complexityLevel: 'Intermedio',
    formativeAction: 'Evaluar',
    modality: 'Práctica',
    icon: 'UserCircle',
    description: 'Proceso donde el estudiante reflexiona y valora su propio proceso de aprendizaje, identificando fortalezas y áreas de mejora.',
    gridX: 3,
    gridY: 3,
  },
  {
    id: 'coevaluacion',
    atomicNumber: 32,
    symbol: 'Co',
    name: 'Coevaluación',
    evaluationType: 'Coevaluación',
    complexityLevel: 'Intermedio',
    formativeAction: 'Evaluar',
    modality: 'Práctica',
    icon: 'Users',
    description: 'Evaluación mutua entre pares (estudiantes) basada en criterios preestablecidos, fomentando la responsabilidad compartida.',
    gridX: 4,
    gridY: 3,
  },
  {
    id: 'proyecto',
    atomicNumber: 40,
    symbol: 'Pr',
    name: 'Proyecto',
    evaluationType: 'Heteroevaluación',
    complexityLevel: 'Avanzado',
    formativeAction: 'Generar',
    modality: 'Práctica',
    icon: 'Briefcase',
    description: 'Trabajo integrador a largo plazo donde los estudiantes aplican múltiples habilidades para resolver un problema complejo.',
    gridX: 12,
    gridY: 3,
  }
];
